### ISSUE TITLE
Pending improvements

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSimulations.jl#228]
### Known issues pending resolution. 
- [x] Update to PM v0.13.0
- [x] Remove the hack when SemiContinuousFF is used to avoid creating range constraints. Requires #155 
- [x] Change structs used as keys to not mutable
- [x] Use structs to handle common variables #219
- [x] Amend data sets for more rigorous testing. 
- [x] Reduce Code repetition #170 
- [x] Reduce testing to avoid time-outs (already addressed for windows) 
- [x] _build_canonical should use construct_device! to all users to hook into this process.
- [x] Add services #260
